messages:
  confirmed-rule: "&aThank you for confirming that you agree with our rules!"
  rules: "<link>"
  confirm-rules: "&7Please take a minute to read through our rules."
  hover: "&7&oClick to confirm that you agree with our rules."
